// Game images and titles in chronological release order.
export const GAMES: { title: string; image: string }[] = [
  { title: "Virtual Cottage",                   image: "virtualCottage.jpg" },
  { title: "PomoFarm",                          image: "pomoFarm.jpg" },
  { title: "Cozy Time",                         image: "cozyTime.jpg" },
  { title: "Spirit City: Lofi Sessions",        image: "spiritCityLofiSessions.jpg" },
  { title: "Chill Pulse",                       image: "chillPulse.jpg" },
  { title: "PacaPomo",                          image: "pacaPomo.jpg" },
  { title: "Mini Cozy Room: Lo-Fi",             image: "miniCozyRoom.jpg" },
  { title: "gogh: Focus with Your Avatar",      image: "gogh.jpg" },
  { title: "Ithya: Magic Studies",              image: "ithya.jpg" },
  { title: "Sky Dreamer",                       image: "skyDreamer.jpg" },
  { title: "Chill with You : Lo-Fi Story",      image: "chillWithYou.jpg" },
  { title: "On-Together: Virtual Co-Working",   image: "onTogether.jpg" },
  { title: "Lofi Haven",                        image: "lofiHaven.jpg" },
  { title: "Virtual Cottage 2",                 image: "virtualCottage2.jpg" },
  { title: "FocusScape: Lofi Productivity",     image: "focusScape.jpg" },
  { title: "Flowfects",                         image: "flowfects.jpg" },
  { title: "Focus Grove",                       image: "focusGrove.jpg" },
  { title: "Hocus Focus",                       image: "hocusFocus.jpg" },
  { title: "Feather Land",                      image: "featherLand.jpg" },
];
